<?php
if(class_exists('ACF')):
    $menu_accordion = acf_add_options_page([
        'page_title' => 'Gerenciar Acordeão',
        'menu_title' => 'Gerenciar Acordeão',
        'position' => 2,
        'capability' => 'edit_posts',
        'redirect' => true
    ]);

    acf_add_local_field_group([
        'key' => 'group_64c67ea2d6292',
        'title' => 'Gerenciar Acordeão',
        'fields' => [
            [
                'key' => 'field_64c67ef8dac81',
                'label' => 'Itens do acordeão',
                'name' => 'itens_do_acordeao',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'layout' => 'block',
                'pagination' => 0,
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Adicionar item',
                'rows_per_page' => 20,
                'sub_fields' => [
                    [
                        'key' => 'field_64c67ea3dac7f',
                        'label' => 'Cor de fundo',
                        'name' => 'cor_de_fundo',
                        'aria-label' => '',
                        'type' => 'color_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '#FF9A33',
                        'enable_opacity' => 1,
                        'return_format' => 'string',
                        'parent_repeater' => 'field_64c67ef8dac81',
                    ],
                    [
                        'key' => 'field_64c67ee1dac80',
                        'label' => 'Cor do texto ao passar o mouse',
                        'name' => 'cor_do_texto_ao_passar_o_mouse',
                        'aria-label' => '',
                        'type' => 'color_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '#ffffff',
                        'enable_opacity' => 1,
                        'return_format' => 'string',
                        'parent_repeater' => 'field_64c67ef8dac81',
                    ],
                    [
                        'key' => 'field_64c67f1bdac82',
                        'label' => 'Ícone',
                        'name' => 'icone',
                        'aria-label' => '',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'return_format' => 'url',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'preview_size' => 'medium',
                        'parent_repeater' => 'field_64c67ef8dac81',
                    ],
                    [
                        'key' => 'field_64c67f38dac83',
                        'label' => 'Título',
                        'name' => 'titulo',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_64c67ef8dac81',
                    ],
                    [
                        'key' => 'field_64c67f40dac84',
                        'label' => 'Texto circulante',
                        'name' => 'texto_circulante',
                        'aria-label' => '',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_64c67ef8dac81',
                    ],
                    [
                        'key' => 'field_64c67f4ddac85',
                        'label' => 'Conteúdo',
                        'name' => 'conteudo',
                        'aria-label' => '',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'layout' => 'block',
                        'pagination' => 0,
                        'min' => 0,
                        'max' => 0,
                        'collapsed' => '',
                        'button_label' => 'Adicionar conteúdo',
                        'rows_per_page' => 20,
                        'sub_fields' => [
                            [
                                'key' => 'field_64c67f68dac86',
                                'label' => 'Texto',
                                'name' => 'texto',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'parent_repeater' => 'field_64c67f4ddac85',
                            ],
                            [
                                'key' => 'field_64c67f91dac87',
                                'label' => 'Post',
                                'name' => 'post',
                                'aria-label' => '',
                                'type' => 'relationship',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'post_type' => '',
                                'taxonomy' => '',
                                'filters' => [
                                    0 => 'search',
                                    1 => 'post_type',
                                ],
                                'return_format' => 'object',
                                'min' => '1',
                                'max' => '1',
                                'elements' => '',
                                'parent_repeater' => 'field_64c67f4ddac85',
                            ],
                        ],
                        'parent_repeater' => 'field_64c67ef8dac81',
                    ],
                ],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-gerenciar-acordeao',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ]);

endif;
